tanyagupta0201/LeetCode-Problems-Solutions

C++/863_AllNodesDistanceKinBinaryTree.cpp
**Add 863. Leetcode qn solution with explanation in comment** 
**863. All Nodes Distance K in Binary Tree**
Closes #2
=> Add 863. Leetcode qn solution with explanation in comment 

C++/263_UglyNumber.cpp
=> Added 263 Ugly number

C++/48_RotateImage.cpp
=> 48 Rotate Image added

C++/94_BinaryTreeInorderTraversal.cpp
=> 94_BinaryTreeInorderTraversal

C++/45_JumpGame2.cpp
**_Solution for Leetcode Problem: 45_JumpGame2 has been added._**
Problem link: https://leetcode.com/problems/jump-game-ii/
Language used: C++ 14
=> Added problem number 45 Jump Game 2 in C++

JAVA/56_MergeIntervals.java
Mam, kindly checkout the solution for the stated problem. I have myself created this solution.
It beats 83.8% solutions in time complexity and 94.3% solutions in space complexity.
=> Solution for Merge Intervals (Leetcode problem 56)

C++/75_SortColors.cpp
=> Added Sort Colors

C++/44_WildcardMatching.cpp
=> Added Wildcard Matching

C++/1881_MaximumValueAfterInsertion.cpp
=> Updated 1881_MaximumValueAfterInsertion.cpp 

C++/1881_MaximumValueAfterInsertion.cpp
Added 1881_MaximumValueAfterInsertion.cpp solution as per the issue assigned. Please add the hacktoberfest-accepted label.
=> Added 1881_MaximumValueAfterInsertion.cpp

C++/21_MergeTwoSortedLists.cpp
Problem No: 21
Problem Name: Merge Two Sorted Lists
=> My first commit in this repository.

C++/18_4Sum.cpp
=> 4SUM solution added

142_LinkedListCycleII.cpp
=> 142. Linked List Cycle II

C++/91_DecodeWays.cpp
=> solution for problem no. 91 decode ways

C++/61_RotateList.cpp
=> 61. Rotate List

C++/54_spiralMatrix.cpp
@tanyagupta0201  Please merged my PR
=> 54_spiralMatrix.cpp

JAVA/198_HouseRobber.java, JAVA/198_house_robber.java
Space optimised program, better than memoisation.
Fixes #165
=> Added prob 198 house robber in java

JAVA/213_HouseRobber2.java
=> Added problem 213 house robber 2 in java

C++/124_BinaryTreeMaximumPathSum.cpp
=> Max Path Sum Updated code

C++/199_BinaryTreeRightSideView.cpp
=> Right View Updated

C++/84_LargestRectangleInHistogram.cpp
Kindly approve my pull request as I have followed all guidelines specified.
Thank you Mam.
=> I have Added Leetcode 84. 

C++/623_AddOneRowtoTree.cpp
c++ solution added with comments
=> solution added

C++/300_LongestIncreasingSubsequence.cpp
300_LongestIncreasingSubsequence solution added
=> added solution to issue #287

JAVA/543_DiameterOfBinaryTree.java
Tried to include documentation for proper understanding of logic.
Fixing the issue #164
=> Added problem 543 diameter of binary tree in java

C++/33_SearchinRotatedSortedArray.cpp
Kindly Check .
Issue Number #257
=> Added the Solution

C++/2425_BitwiseXORofAllPairings.cpp
Please review it ,
Is it ok or I need to change something
=> formatted the code

C++/141_LinkedListCycle.cpp
Fix for issue #301 Added code for Leetcode problem 141 Linked List Cycle.
@tanyagupta0201 please review my pull request and add hacktoberfest-accepted label.
=> #301 Fix leetcode 141 Linked List Cycle

C++/987_Vertical_Order_Traversal_of_a_Binary_Tree.cpp
added solution to the problem 987, kindly merge it under the label 'hacktoberfest-accepted' and 'hacktoberfest'
=> added solution to the problem 987

JAVA/1313_DecompressRun-LengthEncodedList.java
Please accept the pull request for the contribution.
=> JAVA code for issue #330 (LeetCode problem: (1313_DecompressRun-LengthEncodedList)

C++/46_Permutations.cpp
added solution for issue #160 (Permutations)
=> Added solution for 46_Permutations

C++/463_IslandPerimeter.cpp, C++/572_SubtreeOfAnotherTree.cpp, C++/934_ShortestBridge.cpp
I have added the solution pls check it and if correct give hacktoberfest-accepted .Thanks:)
=> added solution to issue #318

JAVA/190_ReverseBits.java, JAVA/2200_FindAllK-DistantIndicesInAnArray.java
Please review the code and if no changes are required then merge the pull request.
=> Java solution for issue #358 (2200 Find All K-distant indices in an array)

JAVA/32_LongestValidParentheses.java
Added solution for Longest Valid Parentheses
=> Added solution for #32 in JAVA

C++/122_BestTimeToBuyAndSellStockII.cpp
122_BestTimeToBuyandSellStockII
=> Added solution to the issue #335

JAVA/9_PalindromeNumber.java
Please review my code and if no changes required merge the pull request.
=> Java solution for issue #392 (Palindrome Number)

JAVA/222_CountCompleteTreeNodes.java
Program to Count Complete Tree Nodes in Java
=> Added solution for #222 in JAVA

C++/630_CourseScheduleIII.cpp
@tanyagupta0201 Please merge my PR under Hacktoberfest.
Issue https://github.com/tanyagupta0201/LeetCode-Problems-Solutions/issues/407
Thanks!
=> code for issue #407

C++/2401_LongestNiceSubarray.cpp
C++ Solution for problem 2401. Longest Nice Subarray
=> added solution to the issue #395 (2401. Longest Nice Subarray)

C++/1219_PathWithMaximumGold.cpp
I have added solution to issue #402 .Pls review it and kindly give hacktoberfest-accepted label. Thanks:)
=> added solution to issue #402

561_ArrayPartition.java
Please review the code and if no changes are required merge the pull request.
=> Code for issue #414

JAVA/1044_LongestDuplicateSubstring.java
Problem Statement :
1044. Longest Duplicate Substring (LEETCODE - HARD)
Given a string s, consider all duplicated substrings: (contiguous) substrings of s that occur 2 or more times. 
The occurrences may overlap.
Return any duplicated substring that has the longest possible length. 
If s does not have a duplicated substring, the answer is "".
Example 1:
Input: s = "banana"
Output: "ana"
Explanation: The answer is "ana", with the length of 3 because "ana" is repeated twice at index 1,3.
Example 2:
Input: s = "abcd"
Output: ""
Explanation: The answer is empty string ("") as there is no duplicate substring
Solution Explanation :-
We can solve this problem by using Rolling Hash with Binary Search
Since the length of the answer is in between 0 to the length of string minus 1, 
In the example …
=> Added problem 1044 of leetcode

C++/790_DominoAndTrominoTiling.cpp
I have added solution to issue #426 .Pls review it and kindly give it hacktoberfest-accepted label. Thanks:).
=> added solution to issue #426

C++/354_RussianDollEnvelopes.cpp
C++ Solution for problem 354. Russian Doll Envelopes
=> added solution to the issue #429 (354. Russian Doll Envelopes)

C++/935_KnightDialer.cpp
I have added solution to issue #447 .Pls review it and kindly merge it and give hacktoberfest-accepted label. Thanks:).
=> added solution to issue #447

C++/31_NextPemutation.cpp
=> added Next Permutation

C++/658_FindKClosestElements.cpp
#367 Find K Closest Elements solved in cpp
=> Find k closest elements

C++/1363_LargestMultipleOfThree.cpp
Issue #454 
Please Review and merge :)
=> 1363. Largest Multiple Of three

C++/53_MaximumSubarray, C++/53_MaximumSubarray.cpp
=> 53_MaximumSubarray

JAVA/328_OddEvenLinkedList.java
Added solution to LeetCode problem:- 328. Odd Even Linked List (Issue #511)
=> 328. Odd Even Linked List

C++/1905_CountSubIslands.cpp
I have added solution to issue #401 .Pls review it and kindly give hacktoberfest-accepted. Thanks:).
=> added solution to issue #401

JAVA/66_PlusOne.java
Added solution to LeetCode problem:- 66. Plus One (Issue #528)
=> 66 plus one

JAVA/1422_MaximumScoreAfterSplittingAString.java
Please merge the pull request.
=> Pull request for issue no. #517

JAVA/932_BeautifulArray.java
please merge this pull request.
=> Pull request for issue no. #534 (Leetcode problem No. - 932. Beautiful Array)

PYTHON/1662_CheckIfTwoStringArraysAreEquivalent.py
Hi @tanyagupta0201 
I have added the python code for leetcode problem 1662.
Kindly accept and merge my PR under hacktoberfest labels.
Regards
=> Solved Issue #542

C++/28_FindTheIndexOfTheFirstOccurenceInAString.cpp
Please merge my PR under Hactoberfest label. Thankyou!
=> C++ Solution added for issue #544

C++/299_BullsAndCows.cpp
Please merge my PR under Hactoberfest labels. Thankyou!
=> C++ Solution added for issue #547

C++/450_DeleteNodeInABST.cpp
Please merge my PR under Hactoberfest labels. Thankyou!
=> C++ Solution added for issue #548

C++/98_ValidateBinarySearchTree.cpp
Please merge my PR under Hactoberfest labels. Thankyou!
=> C++ Solution added for issue #545

C++/150_EvaluateReversePolishNotation.cpp
Please merge my PR under Hactoberfest labels. Thankyou!
=> C++ Solution added for issue #546

JAVA/160_IntersectionOfTwoLinkedList.java, PYTHON/155_MinStack.py
Added the solution of Intersection of Two linked Lists in java
=> Added the solution of Intersection of Two linked Lists in java

C++/1044_LongestDuplicateSubstring.cpp
C++ solution for 1044. Longest Duplicate Substring
=> issue-#578 1044. Longest Duplicate Substring (C++ Solution) 

JAVA/752_OpenTheLock.java
Added Solution for problem 752 of Leetcode
=> Added Solution for problem 752 of Leetcode

JAVA/131_PalindromePartitioning.java
JAVA Solution for 131.Palindrome Partitioning
=> issue-#586 Created 131_PalindromePartitioning.java #586

JAVA/60_PermutationSequence.java, JAVA/60_Permutation_Sequence.java
JAVA Solution for 60. Permutation Sequence
=> issue-#585 Created 60. Permutation Sequence.java #585

JAVA/35_SearchInsertPosition.java
Added the solution of leetcode problem 35 Search insert position in java.
=> Added the solution of leetcode problem 35 Search insert position in java

PYTHON/168_ExcelSheetColumnTitle.py
Added the solution of the leetcode problem 168- Excel Sheet Column Title in Python
=> Added the solution of the leetcode problem 168 in Python

PYTHON/456_132Pattern.py
@tanyagupta0201 ma'am I have added the solution to leetcode problem : https://leetcode.com/problems/132-pattern/  for hacktoberfest2022.
Please verify the code and approve the merge request.
Signed-off-by: Dushyant100 <dushyant01agra@gmail.com>
=> added leetcode 456_132Pattern solution

PYTHON/226_InvertBinaryTree.py
solution for Invert Binary Tree problem in Python 
issue #615
=> problem solution for issue #615
